name: Elegant-tex CI

on:
  push:
    branches:
      - "stage"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build

